/**
 * 设计令牌 → CSS 变量 / SCSS 生成脚本
 * 唯一事实源：packages/shared/src/tokens.ts
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  PRIMITIVE_GRADIENTS,
  SEMANTIC_LIGHT,
  SEMANTIC_TO_CSS,
  SPACING,
  RADIUS,
  SHADOW,
  Z_INDEX,
  MOTION,
  TYPOGRAPHY,
} from '../packages/shared/src/tokens'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const outPath = join(root, 'packages/ui/src/styles/tokens.generated.scss')

function toScssVars(map: Record<string, string>, prefix = '$pilot-'): string {
  return Object.entries(map)
    .map(([k, v]) => `${prefix}${k}: ${v};`)
    .join('\n')
}

function toCssVars(map: Record<string, string>, indent = ''): string {
  return Object.entries(map)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join('\n')
}

/** camelCase 语义键 → CSS 变量名 */
const semanticCss: Record<string, string> = {}
for (const [k, v] of Object.entries(SEMANTIC_LIGHT)) {
  const cssName = (SEMANTIC_TO_CSS as Record<string, string>)[k] ?? k
  semanticCss[cssName] = v
}

/** 渐变 → pilot-gradient-* */
const gradients: Record<string, string> = {}
for (const [k, v] of Object.entries(PRIMITIVE_GRADIENTS)) {
  gradients[`gradient-${k}`] = v
}
gradients['gradient-custom'] = PRIMITIVE_GRADIENTS.aurora

const header = `// AUTO-GENERATED by scripts/gen-tokens.ts — DO NOT EDIT
// Source of truth: packages/shared/src/tokens.ts
`

const scss = `${header}

// ── Primitive ─────────────────────────────────────────────
${toScssVars(gradients)}

// ── Semantic (light) ──────────────────────────────────────
${toScssVars(semanticCss)}

// ── Spacing / Radius / Shadow / Z / Motion / Type ─────────
${toScssVars({ ...SPACING, ...RADIUS, ...SHADOW, ...Z_INDEX, ...MOTION, ...TYPOGRAPHY })}

// ── CSS custom properties (runtime) ───────────────────────
@mixin pilot-css-vars {
  :root {
${toCssVars(gradients, '    ')}
${toCssVars(semanticCss, '    ')}
${toCssVars({ ...SPACING, ...RADIUS, ...SHADOW, ...Z_INDEX, ...MOTION, ...TYPOGRAPHY }, '    ')}

    /* glass */
    --glass-bg: color-mix(in srgb, var(--color-bg-elevated) 72%, transparent);
    --glass-blur: 20px;
    --glass-border: 1px solid color-mix(in srgb, var(--color-border-default) 60%, transparent);
  }

  @media (prefers-reduced-motion: reduce) {
    :root {
      --dur-instant: 0.01ms;
      --dur-fast: 0.01ms;
      --dur-base: 0.01ms;
      --dur-slow: 0.01ms;
      --dur-slower: 0.01ms;
    }
  }

  :root[data-reduce-motion='true'] {
    --dur-instant: 0.01ms;
    --dur-fast: 0.01ms;
    --dur-base: 0.01ms;
    --dur-slow: 0.01ms;
    --dur-slower: 0.01ms;
  }
}
`

async function main() {
  await mkdir(dirname(outPath), { recursive: true })
  await writeFile(outPath, scss, 'utf8')
  console.log(`[gen-tokens] wrote ${outPath}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
