/**
 * 设计令牌 → CSS 变量 / SCSS 生成脚本
 * 源：packages/ui/src/tokens/*（唯一事实源）
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const outPath = join(root, 'packages/ui/src/styles/tokens.generated.scss')

const primitive = {
  gradientAurora: 'linear-gradient(135deg, #22D3EE 0%, #6366F1 50%, #A855F7 100%)',
  gradientSunset: 'linear-gradient(135deg, #FB7185 0%, #F59E0B 100%)',
  gradientOcean: 'linear-gradient(135deg, #38BDF8 0%, #0EA5E9 50%, #2563EB 100%)',
  gradientForest: 'linear-gradient(135deg, #34D399 0%, #10B981 50%, #059669 100%)',
}

const semanticLight = {
  'color-bg-canvas': '#F7F8FB',
  'color-bg-surface': '#FFFFFF',
  'color-bg-elevated': '#FFFFFF',
  'color-bg-sunken': '#EFF1F6',
  'color-bg-hover': 'rgba(15, 23, 42, 0.04)',
  'color-bg-active': 'rgba(99, 102, 241, 0.10)',
  'color-text-primary': '#0F172A',
  'color-text-secondary': '#475569',
  'color-text-tertiary': '#94A3B8',
  'color-text-inverse': '#FFFFFF',
  'color-text-link': '#4F46E5',
  'color-border-subtle': '#EDEFF4',
  'color-border-default': '#E2E5EC',
  'color-border-strong': '#CBD2DE',
  'color-success': '#16A34A',
  'color-warning': '#D97706',
  'color-danger': '#DC2626',
  'color-info': '#0EA5E9',
  'color-accent': '#6366F1',
  'color-accent-hover': '#4F46E5',
  'color-accent-soft': 'rgba(99, 102, 241, 0.12)',
}

const spacing = {
  'space-1': '4px',
  'space-2': '8px',
  'space-3': '12px',
  'space-4': '16px',
  'space-5': '20px',
  'space-6': '24px',
  'space-8': '32px',
  'space-10': '40px',
  'space-16': '64px',
}

const radius = {
  'radius-xs': '6px',
  'radius-sm': '8px',
  'radius-md': '12px',
  'radius-lg': '16px',
  'radius-xl': '20px',
  'radius-full': '9999px',
}

const shadow = {
  'shadow-xs': '0 1px 2px rgba(15,23,42,.06)',
  'shadow-sm': '0 2px 6px rgba(15,23,42,.08)',
  'shadow-md':
    '0 6px 16px -4px rgba(15,23,42,.12), 0 2px 6px -2px rgba(15,23,42,.08)',
  'shadow-lg': '0 16px 40px -12px rgba(15,23,42,.22)',
  'shadow-glow':
    '0 0 0 1px var(--color-border-default), 0 8px 32px -8px var(--color-accent-soft)',
}

const z = {
  'z-base': '0',
  'z-dropdown': '1000',
  'z-sticky': '1100',
  'z-drawer': '1200',
  'z-modal': '1300',
  'z-toast': '1400',
  'z-tooltip': '1500',
  'z-command': '1600',
}

const motion = {
  'dur-instant': '80ms',
  'dur-fast': '140ms',
  'dur-base': '220ms',
  'dur-slow': '320ms',
  'dur-slower': '480ms',
  'ease-standard': 'cubic-bezier(.2, 0, 0, 1)',
  'ease-decelerate': 'cubic-bezier(0, 0, 0, 1)',
  'ease-accelerate': 'cubic-bezier(.3, 0, 1, 1)',
  'ease-spring': 'cubic-bezier(.34, 1.56, .64, 1)',
  'ease-emphasized': 'cubic-bezier(.2, 0, 0, 1)',
}

const typography = {
  'font-sans':
    "'Inter Variable','HarmonyOS Sans SC','PingFang SC','Microsoft YaHei UI',system-ui,sans-serif",
  'font-mono': "'Cascadia Mono','JetBrains Mono','Fira Code',Consolas,monospace",
}

function toScssVars(map: Record<string, string>, indent = ''): string {
  return Object.entries(map)
    .map(([k, v]) => `${indent}$pilot-${k}: ${v};`)
    .join('\n')
}

function toCssVars(map: Record<string, string>, indent = ''): string {
  return Object.entries(map)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join('\n')
}

const header = `// AUTO-GENERATED by scripts/gen-tokens.ts — DO NOT EDIT
// Source of truth: scripts/gen-tokens.ts (primitive/semantic tables)
`

const scss = `${header}

// ── Primitive ─────────────────────────────────────────────
${toScssVars(primitive)}

// ── Semantic (light) ──────────────────────────────────────
${toScssVars(semanticLight)}

// ── Spacing / Radius / Shadow / Z / Motion / Type ─────────
${toScssVars(spacing)}
${toScssVars(radius)}
${toScssVars(shadow)}
${toScssVars(z)}
${toScssVars(motion)}
${toScssVars(typography)}

// ── CSS custom properties (runtime) ───────────────────────
@mixin pilot-css-vars {
  :root {
${toCssVars(primitive, '    ')}
${toCssVars(semanticLight, '    ')}
${toCssVars(spacing, '    ')}
${toCssVars(radius, '    ')}
${toCssVars(shadow, '    ')}
${toCssVars(z, '    ')}
${toCssVars(motion, '    ')}
${toCssVars(typography, '    ')}

    /* glass */
    --glass-bg: color-mix(in srgb, var(--color-bg-elevated) 72%, transparent);
    --glass-blur: 20px;
    --glass-border: 1px solid color-mix(in srgb, var(--color-border-default) 60%, transparent);
  }

  @media (prefers-reduced-motion: reduce) {
    :root {
      --dur-instant: 0.01ms;
      --dur-fast: 0.01ms;
      --dur-base: 0.01ms;
      --dur-slow: 0.01ms;
      --dur-slower: 0.01ms;
    }
  }

  :root[data-reduce-motion='true'] {
    --dur-instant: 0.01ms;
    --dur-fast: 0.01ms;
    --dur-base: 0.01ms;
    --dur-slow: 0.01ms;
    --dur-slower: 0.01ms;
  }
}
`

async function main() {
  await mkdir(dirname(outPath), { recursive: true })
  await writeFile(outPath, scss, 'utf8')
  console.log(`[gen-tokens] wrote ${outPath}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
